// Admin Auth
export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'

// Admin Roles
export const ADMIN_ROLE_LIST_REQUEST = 'ADMIN_ROLE_LIST_REQUEST'
export const ADMIN_ROLE_LIST_SUCCESS = 'ADMIN_ROLE_LIST_SUCCESS'
export const ADMIN_ROLE_LIST_FAIL = 'ADMIN_ROLE_LIST_FAIL'

export const ADMIN_ROLE_DETAILS_REQUEST = 'ADMIN_ROLE_DETAILS_REQUEST'
export const ADMIN_ROLE_DETAILS_SUCCESS = 'ADMIN_ROLE_DETAILS_SUCCESS'
export const ADMIN_ROLE_DETAILS_FAIL = 'ADMIN_ROLE_DETAILS_FAIL'

export const ADMIN_ROLE_CREATE_REQUEST = 'ADMIN_ROLE_CREATE_REQUEST'
export const ADMIN_ROLE_CREATE_SUCCESS = 'ADMIN_ROLE_CREATE_SUCCESS'
export const ADMIN_ROLE_CREATE_FAIL = 'ADMIN_ROLE_CREATE_FAIL'

export const ADMIN_ROLE_UPDATE_REQUEST = 'ADMIN_ROLE_UPDATE_REQUEST'
export const ADMIN_ROLE_UPDATE_SUCCESS = 'ADMIN_ROLE_UPDATE_SUCCESS'
export const ADMIN_ROLE_UPDATE_FAIL = 'ADMIN_ROLE_UPDATE_FAIL'

export const ADMIN_ROLE_DELETE_REQUEST = 'ADMIN_ROLE_DELETE_REQUEST'
export const ADMIN_ROLE_DELETE_SUCCESS = 'ADMIN_ROLE_DELETE_SUCCESS'
export const ADMIN_ROLE_DELETE_FAIL = 'ADMIN_ROLE_DELETE_FAIL'

// Admin Permissions
export const ADMIN_PERMISSION_LIST_REQUEST = 'ADMIN_PERMISSION_LIST_REQUEST'
export const ADMIN_PERMISSION_LIST_SUCCESS = 'ADMIN_PERMISSION_LIST_SUCCESS'
export const ADMIN_PERMISSION_LIST_FAIL = 'ADMIN_PERMISSION_LIST_FAIL'
