export const BRAND_LIST_REQUEST = 'BRAND_LIST_REQUEST'
export const BRAND_LIST_SUCCESS = 'BRAND_LIST_SUCCESS'
export const BRAND_LIST_FAIL = 'BRAND_LIST_FAIL'

export const BRAND_DETAILS_REQUEST = 'BRAND_DETAILS_REQUEST'
export const BRAND_DETAILS_SUCCESS = 'BRAND_DETAILS_SUCCESS'
export const BRAND_DETAILS_FAIL = 'BRAND_DETAILS_FAIL'

export const BRAND_VERIFIED_REQUEST = 'BRAND_VERIFIED_REQUEST'
export const BRAND_VERIFIED_SUCCESS = 'BRAND_VERIFIED_SUCCESS'
export const BRAND_VERIFIED_FAIL = 'BRAND_VERIFIED_FAIL'
