export const CERTIFICATION_LIST_REQUEST = 'CERTIFICATION_LIST_REQUEST'
export const CERTIFICATION_LIST_SUCCESS = 'CERTIFICATION_LIST_SUCCESS'
export const CERTIFICATION_LIST_FAIL = 'CERTIFICATION_LIST_FAIL'

export const CERTIFICATION_DETAILS_REQUEST = 'CERTIFICATION_DETAILS_REQUEST'
export const CERTIFICATION_DETAILS_SUCCESS = 'CERTIFICATION_DETAILS_SUCCESS'
export const CERTIFICATION_DETAILS_FAIL = 'CERTIFICATION_DETAILS_FAIL'

export const CERTIFICATION_BY_TYPE_REQUEST = 'CERTIFICATION_BY_TYPE_REQUEST'
export const CERTIFICATION_BY_TYPE_SUCCESS = 'CERTIFICATION_BY_TYPE_SUCCESS'
export const CERTIFICATION_BY_TYPE_FAIL = 'CERTIFICATION_BY_TYPE_FAIL'
